"""empty message

Revision ID: c96ba9ef8a50
Revises: 
Create Date: 2023-07-20 11:39:10.621859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c96ba9ef8a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.drop_index('name', table_name='categoria')
    op.drop_table('categoria')
    op.drop_index('name', table_name='produto')
    op.drop_table('produto')
    op.drop_index('email', table_name='usuario')
    op.drop_index('username', table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.Column('recovery_code', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role'], ['role.id'], name='usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'usuario', ['username'], unique=False)
    op.create_index('email', 'usuario', ['email'], unique=False)
    op.create_table('produto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('qtd', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_created', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categoria.id'], name='produto_ibfk_2'),
    sa.ForeignKeyConstraint(['user_created'], ['usuario.id'], name='produto_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'produto', ['name'], unique=False)
    op.create_table('categoria',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'categoria', ['name'], unique=False)
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=False)
    # ### end Alembic commands ###
